In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data =pd.read_csv('../../data/dirty_data/DEBT_EU.csv',sep = ';', encoding='latin')

In [3]:
for col in data.columns:
    data[col] = data[col].str.split(',', expand=True)[0].str.replace('\.', '')

/var/folders/6_/c1yy797x7w7g6g9sl3c4rqmw0000gn/T/ipykernel_64719/1936806075.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data[col] = data[col].str.split(',', expand=True)[0].str.replace('\.', '')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 84 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ï»¿Government consolidated gross debt  31 non-null     object
 1   2002-Q1                                31 non-null     object
 2   2002-Q2                                31 non-null     object
 3   2002-Q3                                31 non-null     object
 4   2002-Q4                                31 non-null     object
 5   2003-Q1                                31 non-null     object
 6   2003-Q2                                31 non-null     object
 7   2003-Q3                                31 non-null     object
 8   2003-Q4                                31 non-null     object
 9   2004-Q1                                31 non-null     object
 10  2004-Q2                                31 non-null     object
 11  2004-Q3                                31 non-null     object
 12  2004-Q4                                31 non-null     object
 13  2005-Q1                                31 non-null     object
 14  2005-Q2                                31 non-null     object
 15  2005-Q3                                31 non-null     object
 16  2005-Q4                                31 non-null     object
 17  2006-Q1                                31 non-null     object
 18  2006-Q2                                31 non-null     object
 19  2006-Q3                                31 non-null     object
 20  2006-Q4                                31 non-null     object
 21  2007-Q1                                31 non-null     object
 22  2007-Q2                                31 non-null     object
 23  2007-Q3                                31 non-null     object
 24  2007-Q4                                31 non-null     object
 25  2008-Q1                                31 non-null     object
 26  2008-Q2                                31 non-null     object
 27  2008-Q3                                31 non-null     object
 28  2008-Q4                                31 non-null     object
 29  2009-Q1                                31 non-null     object
 30  2009-Q2                                31 non-null     object
 31  2009-Q3                                31 non-null     object
 32  2009-Q4                                31 non-null     object
 33  2010-Q1                                31 non-null     object
 34  2010-Q2                                31 non-null     object
 35  2010-Q3                                31 non-null     object
 36  2010-Q4                                31 non-null     object
 37  2011-Q1                                31 non-null     object
 38  2011-Q2                                31 non-null     object
 39  2011-Q3                                31 non-null     object
 40  2011-Q4                                31 non-null     object
 41  2012-Q1                                31 non-null     object
 42  2012-Q2                                31 non-null     object
 43  2012-Q3                                31 non-null     object
 44  2012-Q4                                31 non-null     object
 45  2013-Q1                                31 non-null     object
 46  2013-Q2                                31 non-null     object
 47  2013-Q3                                31 non-null     object
 48  2013-Q4                                31 non-null     object
 49  2014-Q1                                31 non-null     object
 50  2014-Q2                                31 non-null     object
 51  2014-Q3                                31 non-null     object
 52  2014-Q4                                31 non-null     object
 53  2015-Q1                                31 non-null     object
 54  2015-Q2                                31 non-null     object
 55  2015-Q3                                31 non-null     object
 56  2015-Q4                                31 non-null     object
 57  2016-Q1                                31 non-null     object
 58  2016-Q2                                31 non-null     object
 59  2016-Q3                                31 non-null     object
 60  2016-Q4                                31 non-null     object
 61  2017-Q1                                31 non-null     object
 62  2017-Q2                                31 non-null     object
 63  2017-Q3                                31 non-null     object
 64  2017-Q4                                31 non-null     object
 65  2018-Q1                                31 non-null     object
 66  2018-Q2                                31 non-null     object
 67  2018-Q3                                31 non-null     object
 68  2018-Q4                                31 non-null     object
 69  2019-Q1                                31 non-null     object
 70  2019-Q2                                31 non-null     object
 71  2019-Q3                                31 non-null     object
 72  2019-Q4                                31 non-null     object
 73  2020-Q1                                31 non-null     object
 74  2020-Q2                                31 non-null     object
 75  2020-Q3                                31 non-null     object
 76  2020-Q4                                31 non-null     object
 77  2021-Q1                                31 non-null     object
 78  2021-Q2                                31 non-null     object
 79  2021-Q3                                31 non-null     object
 80  2021-Q4                                31 non-null     object
 81  2022-Q1                                31 non-null     object
 82  2022-Q2                                31 non-null     object
 83  2022-Q3                                31 non-null     object
dtypes: object(84)
memory usage: 20.5+ KB

In [9]:
data = data.set_index("ï»¿Government consolidated gross debt")

In [11]:
data = data.rename(index={"Germany (until 1990 former territory of the FRG)": "Germany"})

In [13]:
data = data.astype(int)

In [15]:
data

,2002-Q1,2002-Q2,2002-Q3,2002-Q4,2003-Q1,2003-Q2,2003-Q3,2003-Q4,2004-Q1,2004-Q2,...,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3,2021-Q4,2022-Q1,2022-Q2,2022-Q3
ï»¿Government consolidated gross debt,,,,,,,,,,,,,,,,,,,,,
European Union - 27 countries (from 2020),5506467,5546619,5590396,5589363,5725974,5807455,5866319,5846779,6024452,6154226,...,11888100,12072781,12090479,12418930,12639315,12762163,12762414,12995917,13121764,13180283
Euro area â 20 countries (from 2023),5116813,5163853,5192783,5187905,5318408,5401779,5455833,5441799,5601986,5721536,...,11021453,11190409,11161752,11475436,11672317,11796440,11787368,12023819,12148935,12198121
Euro area - 19 countries (2015-2022),5106774,5153824,5182628,5177508,5307348,5390337,5444279,5430177,5589775,5708303,...,10977845,11147215,11117973,11430384,11626731,11750307,11741627,11978574,12103279,12152370
Belgium,295527,293733,292962,288111,297454,296833,295755,285867,300650,300425,...,524244,515878,515168,537303,546530,548189,548488,562175,573668,575009
Bulgaria,10255,9257,9278,8890,8680,8617,8473,8126,8381,8346,...,12846,15269,15131,15273,15723,15824,17009,16231,16441,18708
Czechia,20100,22160,23279,22013,24363,25020,25114,24530,26049,28254,...,84706,79798,81922,96128,98771,95463,103259,110059,112978,121491
Denmark,90372,92399,96599,93174,97587,97072,95842,89061,94680,96542,...,128015,130628,131823,127316,128475,129187,123315,114791,113702,112961
Germany,1285983,1290253,1308782,1317680,1349442,1366466,1389363,1405195,1448336,1457954,...,2261026,2334627,2315216,2345586,2397710,2430788,2471628,2475736,2514916,2527294
Estonia,332,414,423,442,437,460,470,489,480,493,...,5088,5128,5094,5321,5524,5754,5534,5629,5702,5585
Ireland,40934,41857,42853,41987,42188,44143,44319,43409,44985,46927,...,225691,227091,217741,230325,234466,236303,236073,235133,236603,236142
Greece,161507,162757,164471,171410,170278,174153,174592,181510,187837,198359,...,333892,337727,341153,344269,354114,357369,353434,357676,359110,357431
Spain,379002,383191,381131,384145,381976,389134,382788,382775,388781,390340,...,1325133,1342410,1345786,1393076,1424717,1432341,1427238,1453855,1475368,1503799
France,909606,936554,940257,956794,988478,1028178,1043958,1050356,1071942,1106206,...,2634209,2670393,2656153,2745096,2768666,2840922,2821899,2910657,2916834,2956801
Croatia,10038,10028,10155,10397,11060,11442,11554,11622,12210,13232,...,43610,43196,43780,45054,45588,46135,45743,45247,45659,45752
Italy,1460109,1465040,1467742,1436141,1474858,1483887,1502193,1471325,1524971,1566635,...,2530458,2584474,2572756,2650565,2695474,2707227,2678098,2755466,2768877,2743111
Cyprus,6875,7245,7683,7339,7526,7713,8044,8184,8474,9034,...,24414,25379,24852,26044,24879,24820,24271,25158,24180,24002
Latvia,1293,1257,1265,1251,1350,1371,1444,1410,1470,1600,...,12708,13102,12710,13389,13254,13791,14688,14582,15146,15085
Lithuania,3309,3578,3385,3365,3764,3451,3480,3395,3700,3549,...,20132,22417,23062,22563,23115,24160,24535,23308,24224,24036
Luxembourg,1789,1809,1830,1864,1811,1870,1927,1951,1827,1883,...,15083,16534,15878,18368,17805,17808,17733,16790,19313,19213
Hungary,34581,35528,37391,41007,42010,40314,43222,42348,46391,48140,...,93247,95788,105495,107597,111976,116833,114714,119873,116505,113420
Malta,3049,2937,2974,2927,3042,3136,3188,3267,3310,3426,...,6659,6852,6974,7492,8021,7975,8267,8655,8599,8737
Netherlands,243228,246486,245679,244876,252252,251066,256971,256443,263010,266911,...,441900,441582,435459,439971,447923,442903,449026,446419,457624,450573
Austria,157240,156899,157658,151295,158521,162942,158363,152688,160476,168531,...,316344,300993,315980,327417,334902,333103,334162,348606,354609,355611
Poland,88167,80938,83027,84224,82304,83539,82094,83894,89155,94438,...,281873,287457,293124,298868,310206,307124,306837,304244,309882,305115
Portugal,77762,79742,82813,85594,89364,87801,90567,93333,94034,97514,...,259900,267040,270494,275290,277503,271539,269249,275938,280610,279873
Romania,9994,9718,10175,10757,10165,10333,10414,10309,10764,11331,...,88536,92564,102678,102886,106780,112471,116694,120082,125725,130883
Slovenia,6369,6504,6637,6707,6598,6772,6857,6943,7131,7243,...,36889,36716,37422,40156,39469,40140,38877,40244,41053,41752
Slovakia,12885,12515,12303,12273,12153,12495,12569,13125,13702,14304,...,54868,55125,55022,55185,57915,58717,61267,61882,62018,61677
Finland,59970,61047,61773,63299,65850,68461,67427,68508,64653,66964,...,176587,171863,177906,179480,180776,181899,181942,185266,188265,189411
Sweden,136184,132763,137861,141390,142455,140777,145324,146709,147044,145634,...,177735,181679,198565,195437,195079,188831,193228,186829,177606,179595
Norway,55906,57922,63944,72469,75301,79197,78119,80555,82145,94467,...,130529,126770,149360,148345,135501,139575,179089,167718,168397,180363

In [16]:
data.to_csv('DEBT_EU_clean.csv')