In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data= pd.read_csv('../../data/dirty_data/employment.csv',sep = ';', encoding='latin',decimal=",")

In [68]:
data

,Total employment(domestic concept),2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,European Union - 27 countries (from 2020),"188.400,10","188.965,03","189.831,65","191.772,43","195.380,07","199.389,77","201.355,21","197.729,14","195.851,25",...,"194.714,29","196.492,33","198.322,95","200.895,88","204.145,26","207.134,03","209.449,87","206.449,11","209.470,85","213.676,04"
1,European Union - 28 countries (2013-2020),"216.344,00","217.188,10","218.365,10","220.625,58","224.520,52","228.768,52","230.982,77","226.883,41","225.078,11",...,"224.756,06","227.244,84","229.607,99","232.641,20","236.205,43","239.576,99","242.244,45",:,:,:
2,European Union - 15 countries (1995-2004),"172.852,05","173.608,11","174.972,19","176.717,65","179.556,76","182.612,16","184.135,99","180.954,82","180.359,22",...,"180.225,15","182.059,58","183.976,89","186.585,73","189.342,18","192.251,95","194.691,51",:,:,:
3,"Euro area (EA11-1999, EA12-2001, EA13-2007, EA...","137.779,74","138.306,79","139.404,79","140.787,43","143.197,97","146.823,03","148.622,34","148.287,78","147.609,47",...,"147.071,48","149.026,14","151.743,46","153.883,60","156.286,61","158.842,43","160.953,83","158.479,14","160.702,35","164.313,09"
4,Euro area √ê 20 countries (from 2023),"145.715,04","146.358,89","147.465,48","148.939,16","151.547,86","154.413,45","155.742,19","152.823,21","151.919,59",...,"150.758,98","151.891,26","153.305,20","155.449,12","157.890,49","160.487,78","162.649,61","160.154,67","162.397,84","166.048,13"
5,Euro area - 19 countries (2015-2022),"144.166,28","144.773,32","145.867,92","147.326,88","149.885,99","152.700,57","153.994,29","151.086,55","150.249,28",...,"149.256,37","150.348,92","151.743,46","153.883,60","156.286,61","158.842,43","160.953,83","158.479,14","160.702,35","164.313,09"
6,Euro area - 12 countries (2001-2006),"137.779,74","138.306,79","139.404,79","140.787,43","143.197,97","145.846,90","147.057,36","144.535,91","143.906,30",...,"142.798,67","143.833,66","145.110,75","147.123,86","149.403,65","151.807,30","153.823,05","151.460,11","153.675,95","157.066,99"
7,Belgium,"4.175,50","4.171,60","4.212,80","4.273,20","4.321,40","4.393,40","4.471,60","4.464,20","4.492,90",...,"4.559,00","4.577,10","4.617,30","4.675,20","4.748,50","4.818,10","4.895,20","4.898,30","4.989,10","5.088,60"
8,Bulgaria,"3.222,12","3.317,39","3.403,40","3.495,27","3.612,04","3.726,74","3.814,65","3.749,30","3.603,89",...,"3.421,58","3.434,17","3.446,21","3.463,35","3.525,35","3.521,64","3.533,58","3.451,74","3.458,41","3.502,08"
9,Czechia,"4.876,77","4.838,06","4.828,89","4.922,64","4.988,98","5.093,14","5.204,08","5.110,10","5.057,24",...,"5.080,93","5.108,97","5.181,91","5.264,30","5.345,81","5.417,11","5.430,34","5.337,20","5.357,69","5.450,36"
10,Denmark,"2.784,20","2.758,65","2.744,15","2.783,16","2.845,94","2.912,41","2.946,87","2.854,35","2.787,86",...,"2.766,40","2.790,51","2.829,00","2.876,45","2.919,56","2.962,78","3.005,48","2.973,00","3.045,79","3.163,61"
11,Germany (until 1990 former territory of the FRG),"39.666,00","39.237,00","39.362,00","39.311,00","39.595,00","40.272,00","40.838,00","40.903,00","41.048,00",...,"42.350,00","42.721,00","43.122,00","43.661,00","44.251,00","44.866,00","45.277,00","44.915,00","44.980,00","45.570,00"
12,Estonia,"588,50","601,10","598,70","612,30","642,20","643,40","642,10","576,60","548,10",...,"600,90","605,50","622,90","624,70","641,50","647,40","655,60","637,90","638,80","668,10"
13,Ireland,"1.849,26","1.884,74","1.946,14","2.037,01","2.128,25","2.218,60","2.196,67","2.013,43","1.923,01",...,"1.933,23","1.984,01","2.053,49","2.130,13","2.189,97","2.251,53","2.318,23","2.252,62","2.388,72","2.546,85"
14,Greece,"4.434,29","4.495,68","4.604,09","4.646,87","4.731,34","4.795,07","4.856,36","4.829,00","4.706,43",...,"4.300,67","4.453,73","4.322,57","4.469,51","4.446,63","4.650,34","4.751,96","4.666,66","4.793,14","4.975,28"
15,Spain,"17.672,50","18.238,70","18.906,90","19.704,40","20.512,30","21.173,00","21.196,10","19.852,50","19.505,90",...,"17.802,80","17.987,70","18.490,80","18.885,40","19.382,10","19.809,10","20.332,10","19.481,50","19.961,00","20.516,00"
16,France,"26.098,00","26.105,00","26.141,00","26.321,00","26.607,00","26.992,00","27.129,00","26.819,00","26.846,00",...,"27.190,00","27.334,00","27.391,00","27.567,00","27.881,00","28.158,00","28.495,00","28.298,00","29.007,00","29.696,00"
17,Croatia,"1.548,76","1.585,57","1.597,57","1.612,28","1.661,88","1.712,88","1.747,91","1.736,66","1.670,31",...,"1.502,61","1.542,33","1.561,74","1.565,52","1.603,87","1.645,35","1.695,77","1.675,53","1.695,49","1.735,04"
18,Italy,"23.875,40","24.226,20","24.373,30","24.510,80","24.994,40","25.303,60","25.359,70","24.941,80","24.782,80",...,"24.338,80","24.357,30","24.516,20","24.848,70","25.138,30","25.371,30","25.503,90","24.956,10","25.107,50","25.541,70"
19,Cyprus,"328,30","340,11","353,61","366,46","373,25","389,78","403,51","403,64","406,14",...,"370,85","363,41","369,12","386,31","407,14","428,90","445,14","439,86","445,36","458,09"
20,Latvia,"952,32","958,28","960,62","969,15","1.024,95","1.064,07","1.055,07","903,72","843,51",...,"888,63","876,63","889,00","886,30","885,99","898,88","898,06","877,08","854,54","877,97"
21,Lithuania,"1.395,12","1.426,22","1.410,74","1.421,51","1.417,25","1.446,38","1.427,64","1.318,45","1.248,21",...,"1.296,27","1.322,79","1.341,33","1.371,77","1.361,89","1.380,60","1.388,54","1.366,79","1.382,86","1.453,16"
22,Luxembourg,"286,81","292,54","299,31","307,52","319,27","333,26","349,06","352,52","359,02",...,"385,54","395,12","405,24","417,52","432,19","447,72","463,48","471,56","485,57","502,56"
23,Hungary,"4.117,56","4.196,94","4.152,13","4.122,17","4.155,68","4.125,60","4.052,19","3.975,37","3.949,13",...,"4.034,89","4.218,93","4.312,82","4.473,26","4.559,24","4.663,32","4.715,06","4.662,86","4.715,56","4.797,90"
24,Malta,"149,39","148,82","149,37","151,26","153,51","156,95","160,94","161,00","163,79",...,"181,10","192,12","199,40","208,44","225,03","238,60","252,20","259,31","266,87","283,00"
25,Netherlands,"8.427,00","8.380,00","8.285,00","8.340,00","8.521,00","8.772,00","8.915,00","8.839,00","8.779,00",...,"8.733,00","8.725,00","8.808,00","8.943,00","9.157,00","9.408,00","9.623,00","9.571,00","9.759,00","10.146,00"
26,Austria,"3.778,38","3.803,03","3.826,82","3.872,90","3.940,73","4.012,73","4.089,13","4.067,50","4.098,21",...,"4.219,77","4.259,90","4.285,54","4.341,33","4.412,56","4.487,09","4.535,09","4.460,93","4.551,00","4.669,65"
27,Poland,"13.766,30","13.606,10","13.760,30","14.057,00","14.503,90","15.155,90","15.731,90","15.789,40","15.370,30",...,"15.463,80","15.731,00","15.970,00","16.099,70","16.315,00","16.403,70","16.397,90","16.397,60","16.815,00","16.882,80"
28,Portugal,"5.149,93","5.100,19","5.064,18","5.040,96","5.060,86","5.061,58","5.080,13","4.941,69","4.871,33",...,"4.450,17","4.512,99","4.575,82","4.649,86","4.802,60","4.914,02","4.952,80","4.864,72","4.958,72","5.059,40"
29,Romania,"9.573,90","9.569,40","9.187,50","9.159,14","9.353,27","9.488,43","9.359,13","9.017,12","8.725,05",...,"8.569,40","8.634,60","8.525,70","8.429,60","8.631,00","8.638,80","8.649,50","8.472,10","8.624,50","8.635,90"
30,Slovenia,"934,48","931,54","934,37","929,86","944,47","976,12","1.000,53","984,07","963,42",...,"927,71","931,67","943,86","961,19","989,16","1.020,83","1.045,95","1.039,02","1.052,95","1.078,59"
31,Slovakia,"2.038,41","2.060,47","2.055,73","2.088,91","2.132,39","2.176,97","2.247,14","2.203,16","2.169,82",...,"2.192,25","2.223,15","2.267,10","2.321,05","2.372,26","2.419,90","2.445,19","2.399,07","2.385,12","2.427,30"
32,Finland,"2.364,40","2.370,00","2.382,50","2.418,90","2.464,40","2.518,90","2.575,10","2.509,80","2.494,70",...,"2.536,70","2.525,70","2.523,80","2.535,20","2.561,80","2.626,10","2.674,30","2.623,80","2.695,20","2.761,30"
33,Sweden,"4.344,20","4.319,60","4.289,80","4.293,90","4.372,40","4.474,10","4.504,20","4.410,30","4.438,20",...,"4.618,30","4.682,90","4.752,10","4.840,10","4.958,80","5.038,90","5.068,40","5.000,00","5.059,90","5.196,80"
34,Iceland,"148,00","149,10","150,10","161,60","170,30","178,10","179,30","164,60","162,50",...,"171,30","175,50","180,50","188,70","196,70","202,60","202,40","192,80","195,50","210,10"
35,Norway,"2.319,00","2.285,00","2.292,00","2.319,00","2.396,00","2.490,00","2.570,00","2.559,00","2.552,00",...,"2.672,00","2.700,00","2.710,00","2.717,00","2.748,00","2.792,00","2.836,00","2.792,00","2.827,00","2.937,00"
36,Switzerland,"4.117,91","4.103,22","4.114,56","4.144,66","4.234,93","4.344,27","4.448,26","4.469,11","4.481,71",...,"4.736,05","4.825,25","4.899,15","4.967,27","5.012,55","5.064,55","5.101,73","5.076,21","5.105,21","5.179,85"
37,United Kingdom,"27.943,90","28.223,07","28.533,45","28.853,15","29.140,45","29.378,75","29.627,56","29.154,26","29.226,87",...,"30.041,77","30.752,52","31.285,04","31.745,33","32.060,17","32.442,97","32.794,59",:,:,:
38,North Macedonia,"598,52","599,28","559,93","587,48","614,58","632,90","682,96","713,08","687,38",...,"744,84","762,51","776,75","788,92","812,32","813,29","831,07","773,48",:,:

In [69]:
data.replace(':', pd.np.nan, inplace=True)

/var/folders/6_/c1yy797x7w7g6g9sl3c4rqmw0000gn/T/ipykernel_2400/2430488528.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  data.replace(':', pd.np.nan, inplace=True)

In [70]:
data = data.set_index('Total employment(domestic concept)')

In [71]:
for col in data.columns:
    data[col] = data[col].str.split(',', expand=True)[0].str.replace('\.', '')

/var/folders/6_/c1yy797x7w7g6g9sl3c4rqmw0000gn/T/ipykernel_2400/1936806075.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data[col] = data[col].str.split(',', expand=True)[0].str.replace('\.', '')

In [72]:
data = data.dropna(axis=0)

In [73]:
data

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Total employment(domestic concept),,,,,,,,,,,,,,,,,,,,,
European Union - 27 countries (from 2020),188400,188965,189831,191772,195380,199389,201355,197729,195851,195945,...,194714,196492,198322,200895,204145,207134,209449,206449,209470,213676
"Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023)",137779,138306,139404,140787,143197,146823,148622,148287,147609,148407,...,147071,149026,151743,153883,156286,158842,160953,158479,160702,164313
Euro area √ê 20 countries (from 2023),145715,146358,147465,148939,151547,154413,155742,152823,151919,152123,...,150758,151891,153305,155449,157890,160487,162649,160154,162397,166048
Euro area - 19 countries (2015-2022),144166,144773,145867,147326,149885,152700,153994,151086,150249,150518,...,149256,150348,151743,153883,156286,158842,160953,158479,160702,164313
Euro area - 12 countries (2001-2006),137779,138306,139404,140787,143197,145846,147057,144535,143906,144092,...,142798,143833,145110,147123,149403,151807,153823,151460,153675,157066
Belgium,4175,4171,4212,4273,4321,4393,4471,4464,4492,4553,...,4559,4577,4617,4675,4748,4818,4895,4898,4989,5088
Bulgaria,3222,3317,3403,3495,3612,3726,3814,3749,3603,3524,...,3421,3434,3446,3463,3525,3521,3533,3451,3458,3502
Czechia,4876,4838,4828,4922,4988,5093,5204,5110,5057,5043,...,5080,5108,5181,5264,5345,5417,5430,5337,5357,5450
Denmark,2784,2758,2744,2783,2845,2912,2946,2854,2787,2786,...,2766,2790,2829,2876,2919,2962,3005,2973,3045,3163
Germany (until 1990 former territory of the FRG),39666,39237,39362,39311,39595,40272,40838,40903,41048,41544,...,42350,42721,43122,43661,44251,44866,45277,44915,44980,45570
Estonia,588,601,598,612,642,643,642,576,548,584,...,600,605,622,624,641,647,655,637,638,668
Ireland,1849,1884,1946,2037,2128,2218,2196,2013,1923,1885,...,1933,1984,2053,2130,2189,2251,2318,2252,2388,2546
Greece,4434,4495,4604,4646,4731,4795,4856,4829,4706,4505,...,4300,4453,4322,4469,4446,4650,4751,4666,4793,4975
Spain,17672,18238,18906,19704,20512,21173,21196,19852,19505,19010,...,17802,17987,18490,18885,19382,19809,20332,19481,19961,20516
France,26098,26105,26141,26321,26607,26992,27129,26819,26846,27048,...,27190,27334,27391,27567,27881,28158,28495,28298,29007,29696
Croatia,1548,1585,1597,1612,1661,1712,1747,1736,1670,1604,...,1502,1542,1561,1565,1603,1645,1695,1675,1695,1735
Italy,23875,24226,24373,24510,24994,25303,25359,24941,24782,24849,...,24338,24357,24516,24848,25138,25371,25503,24956,25107,25541
Cyprus,328,340,353,366,373,389,403,403,406,407,...,370,363,369,386,407,428,445,439,445,458
Latvia,952,958,960,969,1024,1064,1055,903,843,856,...,888,876,889,886,885,898,898,877,854,877
Lithuania,1395,1426,1410,1421,1417,1446,1427,1318,1248,1255,...,1296,1322,1341,1371,1361,1380,1388,1366,1382,1453
Luxembourg,286,292,299,307,319,333,349,352,359,369,...,385,395,405,417,432,447,463,471,485,502
Hungary,4117,4196,4152,4122,4155,4125,4052,3975,3949,3947,...,4034,4218,4312,4473,4559,4663,4715,4662,4715,4797
Malta,149,148,149,151,153,156,160,161,163,168,...,181,192,199,208,225,238,252,259,266,283
Netherlands,8427,8380,8285,8340,8521,8772,8915,8839,8779,8855,...,8733,8725,8808,8943,9157,9408,9623,9571,9759,10146
Austria,3778,3803,3826,3872,3940,4012,4089,4067,4098,4161,...,4219,4259,4285,4341,4412,4487,4535,4460,4551,4669
Poland,13766,13606,13760,14057,14503,15155,15731,15789,15370,15457,...,15463,15731,15970,16099,16315,16403,16397,16397,16815,16882
Portugal,5149,5100,5064,5040,5060,5061,5080,4941,4871,4776,...,4450,4512,4575,4649,4802,4914,4952,4864,4958,5059
Romania,9573,9569,9187,9159,9353,9488,9359,9017,8725,8522,...,8569,8634,8525,8429,8631,8638,8649,8472,8624,8635
Slovenia,934,931,934,929,944,976,1000,984,963,947,...,927,931,943,961,989,1020,1045,1039,1052,1078
Slovakia,2038,2060,2055,2088,2132,2176,2247,2203,2169,2208,...,2192,2223,2267,2321,2372,2419,2445,2399,2385,2427
Finland,2364,2370,2382,2418,2464,2518,2575,2509,2494,2534,...,2536,2525,2523,2535,2561,2626,2674,2623,2695,2761
Sweden,4344,4319,4289,4293,4372,4474,4504,4410,4438,4540,...,4618,4682,4752,4840,4958,5038,5068,5000,5059,5196
Iceland,148,149,150,161,170,178,179,164,162,164,...,171,175,180,188,196,202,202,192,195,210
Norway,2319,2285,2292,2319,2396,2490,2570,2559,2552,2589,...,2672,2700,2710,2717,2748,2792,2836,2792,2827,2937
Switzerland,4117,4103,4114,4144,4234,4344,4448,4469,4481,4597,...,4736,4825,4899,4967,5012,5064,5101,5076,5105,5179

In [74]:
data= data.astype(int)

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, European Union - 27 countries (from 2020) to Switzerland
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2002    35 non-null     int64
 1   2003    35 non-null     int64
 2   2004    35 non-null     int64
 3   2005    35 non-null     int64
 4   2006    35 non-null     int64
 5   2007    35 non-null     int64
 6   2008    35 non-null     int64
 7   2009    35 non-null     int64
 8   2010    35 non-null     int64
 9   2011    35 non-null     int64
 10  2012    35 non-null     int64
 11  2013    35 non-null     int64
 12  2014    35 non-null     int64
 13  2015    35 non-null     int64
 14  2016    35 non-null     int64
 15  2017    35 non-null     int64
 16  2018    35 non-null     int64
 17  2019    35 non-null     int64
 18  2020    35 non-null     int64
 19  2021    35 non-null     int64
 20  2022    35 non-null     int64
dtypes: int64(21)
memory usage: 6.0+ KB

In [76]:
data.to_csv('employment_clean.csv')